### ISSUE TITLE
`GbParserError` is de-facto private

### ISSUE THREAD

**Issue by althonos** [dlesl/gb-io#2]
Hi David!

In `v0.7.0` I noticed there is no way to use the `GbParserError` type: the `errors` module is private, and this struct is not publicly re-exported in the `::reader` module. I guess it would make sense to re-export it publicly there (the alternative, making `errors` public, only makes sense if you also had the errors from the `::seq` module in there).

**Comment by dlesl** [comment]
Interesting, I'm surprised rust allows this, since it appears in the public API (of the `Iterator` impl), unless I'm missing something...

**Comment by althonos** [comment]
Yes that's actually a trick used to make some traits final/crate-local sometimes, by making them `trait PublicTrait: PrivateTrait` and making `PrivateTrait` private to prevent it from being implemented from outside the crate.

On a side note, I've written bindings for Python (https://github.com/althonos/gb-io.py/): even when requiring copying data in the Python heap it's insanely fast (from x8 to x16 faster than Biopython)!

**Comment by dlesl** [comment]
Ok! #3 should do the trick.

Nice work with the python bindings, the python API looks really nice! I'll add a link to your package in the README.

**Comment by althonos** [comment]
Yes that should do it, thanks!

**Comment by dlesl** [comment]
Released 0.7.1 with this change. BTW I was curious how easy it would be to build `gb-io.py` on NixOS, and it turned out to be very easy so I also took the liberty of opening a [PR](https://github.com/NixOS/nixpkgs/pull/163919) to add it to nixpkgs :)

**Comment by althonos** [comment]
Nice, I'll update the error handling when I get the chance then.

> BTW I was curious how easy it would be to build gb-io.py on NixOS, and it turned out to be very easy so I also took the liberty of opening a https://github.com/NixOS/nixpkgs/pull/163919 to add it to nixpkgs :)

Cool! I'm more of an Arch person (btw, I...) but happy to hear it builds easily. I've reused hack code from another project to bootstrap a temporary `rustc` when installing the package from source if no Rust compiler is found, so in theory it should also be easy to get on Aarch64 or other platforms.

Is Nix one of these package managers that want tests inside the source code? In this case I could also reorganize the project sources to ship with code (like I'm doing with [`pyrodigal`](https://github.com/althonos/pyrodigal) where tests can be invoked from the site install.

**Comment by dlesl** [comment]
The nix build process seems to pick up and run the tests just fine so no changes needed! :)
