### ISSUE TITLE
Feature request: direct access to source fields

### ISSUE THREAD

**Issue by xapple** [dlesl/gb-io#6]
When looking at a GenBank entry there often is interesting information in the "source" feature, which actually contains several subfields. From instance below one can see the "host" information:

<img width="691" alt="host" src="https://github.com/dlesl/gb-io/assets/649288/4308eb09-0b44-4e11-b563-7be9912fd5ab">

I end up having to wrap the `gb_io.Record` class with another class to access this information. Also I end up constantly having to replace newlines with spaces.

    class GenBankRecord:

        def __init__(self, rec):
            """Get a record instance from gb_io"""
            self.rec = rec

        @functools.cached_property
        def source(self):
            """Parse the first feature which is always 'source'"""
            return next(iter(self.rec.features))

        @functools.cached_property
        def fields(self):
            """Get all subfields of source."""
            return self.source.qualifiers.to_dict()

        @functools.cached_property
        def host(self):
            if 'host' in self.fields:
                return self.fields['host'][0].replace('\n', ' ')
            return ''

It would be nice to just do `rec.host` no?

**Comment by dlesl** [comment]
Regarding field access, the python bindings are a [separate project](https://github.com/althonos/gb-io.py), please open an issue there.

The issue with the newlines belongs here though, it's a bit of a tricky one however, see [this issue](https://github.com/dlesl/gb-io/pull/4) for some more discussion.

**Comment by xapple** [comment]
OK I'll post the issue there and close this one. Thanks.
